### ISSUE TITLE
1.1.3.1 trying corerust.dll gnu version: specified procedure not found.

### ISSUE THREAD

**Issue by SkybuckFlying** [radixdlt/babylon-node#933]
Try/test 1: Spaces in folder name of corerust.dll:

```

G:\Tools\Radix\version 1.1.3.1\Node\core-v1.1.3.1\bin>core
2024-05-01T14:47:02,909 [INFO/MemoryLeakDetector/main] - Starting memory leak detector...
2024-05-01T14:47:02,911 [OFF/RadixNodeApplication/main] - Radix distributed ledger 'v1.1.3.1' from branch '' commit 'dc9f98162b383a54b557be4867af4c09394837fe'
2024-05-01T14:47:02,911 [INFO/RuntimeProperties/main] - Loaded properties from default.config
2024-05-01T14:47:03,716 [INFO/RadixNode/main] - Using a genesis of hash 4e7dbd2079a4e0c608a4437a0b51ca383c7f3081038161fa8b1b55d9686797e9
Exception in thread "main" java.lang.UnsatisfiedLinkError: G:\Tools\Radix\version 1.1.3.1\Node\gnu version of corerust.dll\corerust.dll: The specified procedure could not be found
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:287)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2427)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1993)
        at com.radixdlt.environment.NodeConstants.<clinit>(NodeConstants.java:76)
        at com.radixdlt.RadixNodeModule.configure(RadixNodeModule.java:217)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:64)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
        at com.google.inject.spi.Elements.getElements(Elements.java:108)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at com.radixdlt.RadixNode.run(RadixNode.java:106)
        at com.radixdlt.bootstrap.RadixNodeBootstrapper.bootstrapRadixNode(RadixNodeBootstrapper.java:193)
        at com.radixdlt.bootstrap.RadixNodeBootstrapper.runNewNode(RadixNodeBootstrapper.java:104)
        at com.radixdlt.RadixNodeApplication.main(RadixNodeApplication.java:92)

G:\Tools\Radix\version 1.1.3.1\Node\core-v1.1.3.1\bin>
```

**Comment by SkybuckFlying** [comment]
Same result when coretest.dll moved to G:\test folder:


```
G:\Tools\Radix\version 1.1.3.1\Node\core-v1.1.3.1\bin>core
2024-05-01T14:50:32,217 [INFO/MemoryLeakDetector/main] - Starting memory leak detector...
2024-05-01T14:50:32,217 [OFF/RadixNodeApplication/main] - Radix distributed ledger 'v1.1.3.1' from branch '' commit 'dc9f98162b383a54b557be4867af4c09394837fe'
2024-05-01T14:50:32,227 [INFO/RuntimeProperties/main] - Loaded properties from default.config
2024-05-01T14:50:32,967 [INFO/RadixNode/main] - Using a genesis of hash 4e7dbd2079a4e0c608a4437a0b51ca383c7f3081038161fa8b1b55d9686797e9
Exception in thread "main" java.lang.UnsatisfiedLinkError: G:\TEST\corerust.dll: The specified procedure could not be found
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
        at java.base/jdk.internal.loader.NativeLibraries.findFromPaths(NativeLibraries.java:315)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:287)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2427)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:818)
        at java.base/java.lang.System.loadLibrary(System.java:1993)
        at com.radixdlt.environment.NodeConstants.<clinit>(NodeConstants.java:76)
        at com.radixdlt.RadixNodeModule.configure(RadixNodeModule.java:217)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:64)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:409)
        at com.google.inject.spi.Elements.getElements(Elements.java:108)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:160)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at com.radixdlt.RadixNode.run(RadixNode.java:106)
        at com.radixdlt.bootstrap.RadixNodeBootstrapper.bootstrapRadixNode(RadixNodeBootstrapper.java:193)
        at com.radixdlt.bootstrap.RadixNodeBootstrapper.runNewNode(RadixNodeBootstrapper.java:104)
        at com.radixdlt.RadixNodeApplication.main(RadixNodeApplication.java:92)

G:\Tools\Radix\version 1.1.3.1\Node\core-v1.1.3.1\bin>
```
